Allow ReadOnlyMemory<byte> as Lua Script parameter type
StackExchange/StackExchange.Redis pull request #1713
Opened 2021-03-28 14:31 UTC by eduardobr

While `ReadOnlyMemory<byte>` is convertible to `RedisValue`, the type is not allowed as a Lua script parameter.
I can see the restriction doesn't seem to be necessary and the type work as expected on Lua scripts.

How to reproduce:
```
1. const string Script = "return @ident";
2. var prepared = LuaScript.Prepare(Script);
3. var db = conn.GetDatabase();
4. 
5. var val = prepared.Evaluate(db, new { ident = new ReadOnlyMemory<byte>(new byte[] { 4, 5, 6 }) });
6. Assert.True(new byte[] { 4, 5, 6 }.SequenceEqual((byte[])val));
```

Here line 5 will fail with
```
System.ArgumentException : ps
    Parameter name: Expected [ident] on [<>f__AnonymousType3`1[[System.ReadOnlyMemory`1[[System.Byte, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]]] to be convertable to a RedisValue
```

2021-03-28 15:16 UTC, mgravell approved these changes
Looks good. I wonder whether we should also allow Memory-byte and (lower priority) ArraySegment-byte, but ... not urgent, perhaps

2021-03-28 15:44 UTC, mgravell requested changes
On reflection, I think one thing that is important is to ensure that the *basic* (not named parameter) scripting API has the same feature set. It may be worth adding a test that uses vanilla ScriptEvaluate

2021-03-28 16:20 UTC, eduardobr commented
> 
> 
> On reflection, I think one thing that is important is to ensure that the _basic_ (not named parameter) scripting API has the same feature set. It may be worth adding a test that uses vanilla ScriptEvaluate

Added a version that tests ScriptEvaluate from a raw string

2021-03-30 10:12 UTC, mgravell commented on src/StackExchange.Redis/LuaScript.cs
> +                                    throw new ArgumentException("Expected [" + missingMember + "] to be a field or gettable property on [" + psType.FullName + "]", nameof(ps));
nice catch

2021-03-30 10:14 UTC, merged