improving configcheckseconds for a faster failover detection
StackExchange/StackExchange.Redis pull request #1735
Opened 2021-05-23 19:28 UTC by deepakverma

Fixes info command storm on a disconnect
After a master node disconnect performs ConfigCheckSeconds on replica nodes with an exponential backoff

2021-05-25 12:56 UTC, NickCraver requested changes
I think this one's good - would like a name tweak for clarity though please!

2021-05-25 12:56 UTC, NickCraver commented on src/StackExchange.Redis/ServerEndPoint.cs
> +        internal void ForceExponentiallyReplicationCheck()
Can we rename this for clarity please?
```suggestion
        internal void ForceExponentialBackoffReplicationCheck()
```

2021-05-25 20:54 UTC, philon-msft approved these changes

2021-05-26 11:26 UTC, NickCraver approved these changes
:+1: Looking good, thanks for the tweaks!

2021-05-26 11:27 UTC, merged