Implement GETEX command
StackExchange/StackExchange.Redis pull request #1743
Opened 2021-06-02 20:41 UTC by benbryant0

Resolves #1740

Should add support for all current options of [GETEX](https://redis.io/commands/getex).

Questionable (non-)decisions:
* I called the new methods `StringGet[Async]` (consistent with existing methods) as the behaviour is most similar to plain `StringGet` and I think the added expiry functionality is communicated by the parameters.
* The relative expiry overload takes `TimeSpan?` while the absolute overload takes non-nullable `DateTime`. I don't like it, but I did this as I realised I'd have to cast to escape ambiguity: `(TimeSpan?)null` 🤮. But maybe consistency is more important?
* I looked in the `tests` folder and cried a little; I have no idea what I'm supposed to update there. I just bumped the Redis version in `Dockerfile` since Docker is easy and you seem to use it in your GitHub actions.
* I placed the tests in `Strings`, even though they involve expiry and the tests themselves go against the pattern there a bit. Felt better than bloating something catch-all like `BasicOps`.

Please let me know if any of the above could be better/should be changed.

2021-06-03 16:01 UTC, NickCraver commented
I see we need async tests here, but main point that I'm hung on is the API - want to sanity check method names. IMO, `TimeSpan?` feels weird - if we're not setting an expiry shouldn't the user be calling the existing `StringGet`? I wonder if we should call these `StringGetSetExpiry` or something that's a clearer usage pattern, looking at consumer code you could easily assume it's somehow related to a timeout or respecting an existing TTL or something, and not _setting_ a value (admittedly, this is confusing on the base Redis API we're hitting as well).

The async test versions are straightforward, but thoughts on overload nullability and general naming? cc @mgravell

2021-06-03 17:54 UTC, benbryant0 commented
Calling with null for the `TimeSpan?` parameter isn't "not setting an expiry", but removing any existing expiry; it maps to using the `PERSIST` option.

Good point about consuming code being unclear; `StringGetSetExpiry` sounds reasonable to me.

2022-03-27 00:23 UTC, NickCraver commented
I'll work on getting this updated (my fault we haven't gotten to everything) as part of #2055. Current thinking here: slim down to _only_ the `RedisValue StringGetSetExpiry(RedisKey key, TimeSpan expiry, CommandFlags flags = CommandFlags.None);` overload - instead of leaving DateTime conversion in the lib's hands (or assuming what the Redis server has), it's best to stick with the timespan-only overloads as we do elsewhere. Since `TimeSpan.Zero` also serves the removal case, we can remove the multiple overloads for a single Redis command here. I'll work on getting `main` merged in here :)

2022-03-27 02:45 UTC, benbryant0 commented
It seems a shame to lose support for the EXAT/PXAT options, but if you think that's best I see no issue with it.

Just to try and clarify some things again though: If I remember correctly my intent was to stay consistent with `KeyExpireAsync`. The two overloads there map to `EXPIRE` and `EXPIREAT`, but the difference between those commands is represented as options for `GETEX`. Having two optional parameters of the form `TimeSpan? relativeExpiry = null, DateTime? absoluteExpiry = null` just seemed like a nightmare, so I went with an overload (but in hindsight maybe a simple union value type could've made that clean).

I think there's also still misunderstanding about 'removal' and the `TimeSpan?` parameter. As I said, removing refers to removing _the expiry_, not the key (hence the suggested alternative name '...RemoveExpiry'). The `TimeSpan?` parameter & behaviour was consistent with `KeyExpireAsync` (the `GetStringGetExMessage` methods were almost exact copies of `GetExpiryMessage`).

2022-03-27 03:28 UTC, NickCraver commented
@benbryant0 Okay I gotcha - yes good clarifications, and some was lost in merge noise here. Will absolutely re-evaluate with fresh eyes. I really appreciate the follow-up here.

2022-03-27 20:43 UTC, NickCraver commented
@benbryant0 Would you mind eyes on latest when time allows please? I didn't match `KeyExpire` _exactly_ because both versions being nullable makes `Method(key, null)` ambiguous - so instead I made the `DateTime` overload non-nullable.

There's code that can be shared here on converting to milliseconds but will do that in a follow-up PR to keep things tidy.

Thanks for everything here, it's much appreciated!

2022-03-28 02:25 UTC, slorello89 requested changes
Hey @benbryant0  - looks pretty good, just a few things.

1: I think there should be another API specifically for persistence rather than passing in null. I worked backward a bit and read through the code rather than reading your back & forth, I think 3 methods per sync/async would make the most sense here. Fundamentally the command allows 3 things, persist a given amount of time, persist until a time, and persit indefinitely. So this should either be 1 enum Operated method

`StringGetSetExpiry(RedisKey key, ExpiryType type, Timespan? timespan = null, Timestamp? timestamp = null, Commandflags flags = CommandFlags.None)`

or just split it out into 3 methods, which IMO is cleaner and will result in fewer paths, and fewer need for the library to toss exceptions. Sort of thinking the null timespan setting it to persist forever is confusing (I might expect it to have some reasonable default value e.g. 60 seconds, or something configured).

2: There's some extra logic to pull out seconds vs milliseconds I don't think necessary, just use milliseconds, I believe [Redis](https://github.com/redis/redis/blob/23325c135f08365d1b7d4bf4fb1c9187fc7374b9/src/t_string.c#L109) will just use Milliseconds regardless, and you're going to send a 64 bit integer no matter what.

3: Very minor stylistic comments (casing and Assertions) in the tests. Looks like there is one missing test to exercise the off-nominal `ArgumentException` we're adding above.

2022-03-28 02:25 UTC, slorello89 commented on tests/StackExchange.Redis.Tests/Strings.cs
> +            var val_ttl = conn.KeyTimeToLiveAsync(key);
casing.

2022-03-28 02:25 UTC, slorello89 commented on tests/StackExchange.Redis.Tests/Strings.cs
> +            Assert.True(time > TimeSpan.FromMinutes(29.9) && time <= TimeSpan.FromMinutes(30));
use GreaterThan/LessThan assertions rather than true.

2022-03-28 02:25 UTC, slorello89 commented on tests/StackExchange.Redis.Tests/Strings.cs
> +        public async Task GetEx_Persist()
casing.

2022-03-28 02:25 UTC, slorello89 commented on tests/StackExchange.Redis.Tests/Strings.cs
> +            var val_ttl = conn.KeyTimeToLiveAsync(key);
casing.

2022-03-28 02:25 UTC, slorello89 commented on tests/StackExchange.Redis.Tests/Strings.cs
> +
I'd Expect one more test here to try out the path in which you'd throw an [ArgumentException](https://github.com/StackExchange/StackExchange.Redis/pull/1743/files#diff-4dd7cb0578bed18d8797224b2f3a47777d9592d24137357eb7eac71d162508dbR3564) in the case of an `TimeStampKind.Unspecified` timestamp. TBH I'm not even sure what that means :)

2022-03-28 12:09 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        RedisValue StringGetSetExpiry(RedisKey key, TimeSpan? expiry, CommandFlags flags = CommandFlags.None);
So...this was how it was, but that's even less like existing methods, went this route for consistency. In .NET caches, the nullable expiration removing the expiration is a common thing, so I'm comfortable with this.

2022-03-28 12:09 UTC, NickCraver commented on src/StackExchange.Redis/RedisDatabase.cs
> +            if ((milliseconds % 1000) == 0)
I was wondering about this! IMO, let's take this part as-is, and remove this code from _many_ commands all at once - save as getting the milliseconds, there's several de-duping things we can do here.

2022-03-28 12:10 UTC, NickCraver commented on src/StackExchange.Redis/RedisFeatures.cs
> +        public Version Version => version ?? v2_0_0;
This was me in the merge, just put it down bottom after a conflict (I should go through and order these...)

2022-03-28 12:35 UTC, slorello89 commented on src/StackExchange.Redis/RedisDatabase.cs
> +            if ((milliseconds % 1000) == 0)
Ok if this is a matter of precedent, maintaining the pattern is appropriate. Probably just resolve with a separate issue?

2022-03-28 12:37 UTC, slorello89 commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        RedisValue StringGetSetExpiry(RedisKey key, TimeSpan? expiry, CommandFlags flags = CommandFlags.None);
Ahh gotcha, I see it in [`GetExpiryMessage`](https://github.com/StackExchange/StackExchange.Redis/blob/main/src/StackExchange.Redis/RedisDatabase.cs#L2705)

2022-03-28 12:44 UTC, NickCraver commented on src/StackExchange.Redis/RedisDatabase.cs
> +            if ((milliseconds % 1000) != 0)
Ehhhh screw it, made the change here :) Cleaner now!

2022-03-28 17:24 UTC, benbryant0 commented
LGTM!

Thanks for taking another pass at it @NickCraver and applying all the suggestions. Such an improvement over the original.

And thanks @slorello89 for the good input. I agree that a separate method would be nicer; but I think consistency is more important (and this is already a _very_ big interface).

Good point regarding ms vs seconds; if I had even thought of it I wouldn't have done it due to lack of experience with Redis, now I know!

2022-03-28 18:42 UTC, slorello89 approved these changes
Given there's agreement on the API, LGTM 👍

2022-03-28 19:34 UTC, merged