Support LMOVE
StackExchange/StackExchange.Redis pull request #2065
Opened 2022-04-04 12:43 UTC by Avital-Fine

https://redis.io/commands/lmove/

2022-04-04 12:47 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        /// <returns>The element being popped and pushed.</returns>
We should say this may be nil, if there's no element to move.

2022-04-04 12:48 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        /// <param name="whereTo">What side of the list to move to.</param>
```suggestion
        /// <param name="whereFrom">What side of the <paramref name="sourceKey"/> list to remove from.</param>
        /// <param name="whereTo">What side of the <paramref name="destinationKey"/> list to move to.</param>
```

2022-04-04 12:48 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        /// at the first/last element of the list stored at destination.
```suggestion
        /// Returns and removes the first or last element of the list stored at <paramref name="sourceKey"/>, and pushes the element
        /// as the first or last element of the list stored at <paramref name="destinationKey"/>.
```

2022-04-04 12:48 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IDatabaseAsync.cs
> +        /// <remarks>https://redis.io/commands/lmove</remarks>
(Same doc changes as above please!)

2022-04-04 12:49 UTC, NickCraver commented on src/StackExchange.Redis/RedisDatabase.cs
> +            var msg = Message.Create(Database, flags, RedisCommand.LMOVE, sourceKey, destinationKey, whereFrom.ToString(), whereTo.ToString());
`.ToString()` on these allocates on each call - instead we should use a ternary here which never allocates.

2022-04-04 12:49 UTC, NickCraver commented on src/StackExchange.Redis/RedisDatabase.cs
> +            var msg = Message.Create(Database, flags, RedisCommand.LMOVE, sourceKey, destinationKey, whereFrom.ToString(), whereTo.ToString());
Same on allocations.

2022-04-04 12:50 UTC, NickCraver commented on tests/StackExchange.Redis.Tests/Lists.cs
> +            }
We should test both directions as well as what happens when the source/destination lists are null.

2022-04-04 12:50 UTC, NickCraver commented on tests/StackExchange.Redis.Tests/Lists.cs
> +                RedisKey dest = "destinationlist";
These need to use `Me()`, to get unique keys that won't conflict :)

2022-04-04 15:00 UTC, NickCraver commented on src/StackExchange.Redis/Enums/ListSide.cs
> +        Right
```suggestion
        /// <summary>
        /// The head of the list.
        /// </summary>
        Left,
        /// <summary>
        /// The tail of the list.
        /// </summary>
        Right,
```

2022-04-04 15:01 UTC, NickCraver commented
@Avital-Fine for tests, check out the format `Skip.IfMissingFeature(conn, nameof(RedisFeatures.PushMultiple), f => f.PushMultiple);` - we need to so similar for LMOVE there for testing against older servers :)

2022-04-04 15:23 UTC, Avital-Fine commented
> Thanks for this! I left comments inline - note that #2041 is a _major_ change we wanted to get in before tons of PRs here (per #2055) and will make merging a bit difficult. I wanted to throw a note in here in case unaware. I'll do me best to help merge `main` into these after NRTs lands.

Thank you! hope the merge won't be too bad :sweat_smile:

2022-04-08 11:05 UTC, NickCraver requested changes
A few tweaks/removals then I think we're good to go - thanks for this!

2022-04-08 11:05 UTC, NickCraver commented on src/StackExchange.Redis/RedisDatabase.cs
> +            var msg = Message.Create(Database, flags, RedisCommand.LMOVE, sourceKey, destinationKey, whereFrom == ListSide.Left ? "Left" : "right", whereTo == ListSide.Left ? "Left" : "right");
We should be consistent in Left vs right here :)

2022-04-08 11:05 UTC, NickCraver commented on src/StackExchange.Redis/RedisFeatures.cs
> +        public bool ListMove => Version >= v6_2_0;
Let's remove this and move to the IsBelow skip check version in main, can see examples now and in a neighboring PR to make it global!

2022-04-08 11:05 UTC, NickCraver commented on tests/StackExchange.Redis.Tests/Lists.cs
> +                RedisKey key = Me();
Thanks for these fixes btw!

2022-04-10 00:18 UTC, slorello89 approved these changes
LGTM 👍

2022-04-10 12:29 UTC, Avital-Fine commented on tests/StackExchange.Redis.Tests/Lists.cs
> +                RedisKey key = Me();
Sure!

2022-04-10 13:31 UTC, NickCraver approved these changes
👍 Looking good

2022-04-10 13:32 UTC, merged