Support COMMAND [...]
StackExchange/StackExchange.Redis pull request #2143
Opened 2022-05-16 11:46 UTC by shacharPash

2022-05-16 13:34 UTC, NickCraver commented
I just see some trailing spaces on tests to tidy - wanted to comment early this is looking great!

2022-05-18 15:04 UTC, shacharPash commented
@NickCraver 
Ready

2022-05-19 08:59 UTC, chayim commented
Part of #2055

2022-05-21 21:01 UTC, NickCraver requested changes
Trying to catch up a bit - thanks for this! The first set looks good, but I think the second set is split up a bit too much - normally in our API patterns you'd expect 1 command with some arguments for `CommandGetkeys`, so let's collapse that down to the main `CommandGetkeys()` method with string params for the 3 possible filters :)

2022-05-22 08:26 UTC, shacharPash commented on src/StackExchange.Redis/Interfaces/IServer.cs
> +        RedisValue[] CommandGetkeys(RedisValue[] command, CommandFlags flags = CommandFlags.None);
string[] will be better?

2022-05-24 14:06 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IServer.cs
> +        Task<RedisValue[]> CommandListAsync(RedisValue? moduleName = null, RedisValue? category = null, RedisValue? pattern = null, CommandFlags flags = CommandFlags.None);
Let's make this return `string[]` please :)

2022-05-24 14:49 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IServer.cs
> +        RedisValue[] CommandGetkeys(RedisValue[] command, CommandFlags flags = CommandFlags.None);
Pushed some tweaks - all good here now!

2022-05-24 14:49 UTC, NickCraver commented on src/StackExchange.Redis/Interfaces/IServer.cs
> +        Task<RedisValue[]> CommandListAsync(RedisValue? moduleName = null, RedisValue? category = null, RedisValue? pattern = null, CommandFlags flags = CommandFlags.None);
Done!

2022-05-24 15:31 UTC, merged