Adds support for XPENDING IDLE parameter
StackExchange/StackExchange.Redis pull request #2822
Opened 2024-12-05 13:50 UTC by david-brink-talogy

Adds support for[ Idle time filter](https://redis.io/docs/latest/commands/xpending/) on XPENDING command.  

This filter is only available on Redis 6.2+, but I didn't see an indication that version is checked when building command arguments/values.  

fixes #2432

2024-12-05 14:49 UTC, mgravell commented on src/StackExchange.Redis/RedisDatabase.cs
> +            if (minIdleTimeInMs is not null)
👍

2024-12-05 14:49 UTC, mgravell commented on tests/StackExchange.Redis.Tests/KeyPrefixedDatabaseTests.cs
> +        prefixed.StreamPendingMessages("key", "group", 10, RedisValue.Null, "-", "+", 1000, CommandFlags.None);
we probably need a version-check here, to not break test setups

2024-12-05 14:52 UTC, mgravell requested changes
main problem here is the API break - we need to do that differently (see notes)

also: please add to releasenotes.md

2024-12-05 15:23 UTC, mgravell commented on tests/StackExchange.Redis.Tests/KeyPrefixedDatabaseTests.cs
> +        prefixed.StreamPendingMessages("key", "group", 10, RedisValue.Null, "-", "+", 1000, CommandFlags.None);
oh, if it is mocked: fine - ignore me

2024-12-05 16:45 UTC, mgravell approved these changes
*technically* this is a little weird if somebody was passing literal `0` as the `flags` parameter on the old API, which is legal but unusual; I'm OK with it, though - any thoughts from @NickCraver  @philon-msft ?

2025-01-03 12:23 UTC, atakavci commented
> somebody was passing literal 0 as the flags parameter on the old API

@mgravell, how about having a `TimeSpan` instead of a `long` for `min-idle-time`?

2025-01-06 13:35 UTC, david-brink-talogy commented
> > somebody was passing literal 0 as the flags parameter on the old API
> 
> @mgravell, how about having a `TimeSpan` instead of a `long` for `min-idle-time`?

I preferred to mirror the existing APIs around streams.  All use a long.

https://github.com/search?q=repo%3AStackExchange%2FStackExchange.Redis%20idleTimeInMs&type=code

2025-01-10 16:34 UTC, david-brink-talogy commented
> _technically_ this is a little weird if somebody was passing literal `0` as the `flags` parameter on the old API, which is legal but unusual; I'm OK with it, though - any thoughts from @NickCraver @philon-msft ?

@NickCraver @philon-msft, bumping in case this was overlooked during year end.

2025-01-10 17:57 UTC, philon-msft commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, RedisValue? minId = null, RedisValue? maxId = null, long? minIdleTimeI
+1 on this. I'd leave the existing public method signatures as-is, and add new methods with additional required params as needed.

2025-01-10 18:45 UTC, david-brink-talogy commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, RedisValue? minId = null, RedisValue? maxId = null, long? minIdleTimeI
Do you have a suggestion on the overloads?  This Redis API can satisfy a number of use cases depending on the parameters passed.  minIdleTimeInMs can be used with various combinations of consumerName, minId, and maxId if new overloads do not have defaults.  Several overloads would likely be needed to satisfy all use cases which complicates the public API.

With this many arguments I'd generally lean toward an class like StreamPendingMessagesArgs, but that seems to run afoul of the existing design.  

The PR as it currently exists seemed like a reasonable compromise between backwards compatibility and adhering to the design.

2025-01-10 19:51 UTC, philon-msft commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, RedisValue? minId = null, RedisValue? maxId = null, long? minIdleTimeI
I was thinking something like this (but @mgravell and @NickCraver are really the experts):
```cs
StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, long minIdleTimeInMs = null, RedisValue? minId = null, RedisValue? maxId = null, CommandFlags flags = CommandFlags.None);
```

2025-02-01 01:30 UTC, david-brink-talogy commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, RedisValue? minId = null, RedisValue? maxId = null, long? minIdleTimeI
Going to try one last time.  @mgravell , @NickCraver, what would you like to see?  I'm happy to amend the PR if I can get some direction on the desired arguments.

2025-07-24 11:20 UTC, mgravell commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, RedisValue? minId = null, RedisValue? maxId = null, long? minIdleTimeI
@philon-msft  a problem there is that there are awkward implicit operators that would make that ambiguous; the code as shown is *technically* a compile-time-break, but: it only applies in rare scenarios, and is in a way that I'm OK with (move the flags) - I'm going to push ahead as presented

2025-07-24 11:22 UTC, mgravell commented
I think this is good to go "as is"; I'll fix the merge

2025-07-24 11:24 UTC, mgravell commented
@david-brink-talogy  sorry for delay here; good news: this is now my day job, so: we can get things unblocked; thanks for the contribution - much appreciated

2025-07-24 11:25 UTC, mgravell commented on src/StackExchange.Redis/Interfaces/IDatabase.cs
> +        StreamPendingMessageInfo[] StreamPendingMessages(RedisKey key, RedisValue groupName, int count, RedisValue consumerName, RedisValue? minId = null, RedisValue? maxId = null, long? minIdleTimeI
added to that: I'm already doing a "bump", so: good timing

2025-07-24 11:39 UTC, merged